### ISSUE TITLE
Unable to downlaod the WMH dataset 

### ISSUE THREAD

**Issue by Adrija03** [openmedlab/Awesome-Medical-Dataset#1]
Hello! Thank you so much for this very compressive list of available datasets. I am however, unable to download the WMH dataset. I clicked on the download dataset button, but it doesn't seem to want to unzip. Any help is very much appreciated. 
Kind regards, 
Adrija.

**Comment by MengzhangLI** [comment]
Yes, when I click the bottom from: 

It is like:

![image](https://github.com/user-attachments/assets/714b39ce-f2dd-43d7-9102-c8bcd72fe902)

But after I wait patiently, it works:

![image](https://github.com/user-attachments/assets/bdfcd39b-513e-4cf4-af70-4ccccbeafe26)

So I think it is network issue, you should wait patiently and try again.

Best,
